// Easter Egg: 20-Hop Dependency Chain
MATCH (cr1:CustomerRequest {id:"CR001"} )
// New Requirement tied to CR001
CREATE (req36:Requirement {id: "REQ036", title: "Quantum Stability", description: "Ensure quantum flux stability for 10Gbps", status: "Active", source: "Doors"})

// 20 Design Nodes in a Linear Chain
CREATE (des36:Design {id: "DES036", name: "Quantum Initiator", description: "Starts quantum flux", status: "Delayed", source: "Pront"})
CREATE (des37:Design {id: "DES037", name: "Flux Modulator", description: "Modulates flux waves", status: "Delayed", source: "Pront"})
CREATE (des38:Design {id: "DES038", name: "Phase Aligner", description: "Aligns quantum phases", status: "Delayed", source: "Pront"})
CREATE (des39:Design {id: "DES039", name: "Wave Synchronizer", description: "Syncs wave patterns", status: "Delayed", source: "Pront"})
CREATE (des40:Design {id: "DES040", name: "Entanglement Core", description: "Manages entanglement", status: "Delayed", source: "Pront"})
CREATE (des41:Design {id: "DES041", name: "Spin Regulator", description: "Regulates particle spin", status: "Delayed", source: "Pront"})
CREATE (des42:Design {id: "DES042", name: "Coherence Filter", description: "Filters coherence noise", status: "Delayed", source: "Pront"})
CREATE (des43:Design {id: "DES043", name: "Pulse Amplifier", description: "Amplifies quantum pulses", status: "Delayed", source: "Pront"})
CREATE (des44:Design {id: "DES044", name: "Resonance Tuner", description: "Tunes resonance freq", status: "Delayed", source: "Pront"})
CREATE (des45:Design {id: "DES045", name: "Beam Splitter", description: "Splits quantum beams", status: "Delayed", source: "Pront"})
CREATE (des46:Design {id: "DES046", name: "Photon Gate", description: "Gates photon flow", status: "Delayed", source: "Pront"})
CREATE (des47:Design {id: "DES047", name: "Waveguide", description: "Guides quantum waves", status: "Delayed", source: "Pront"})
CREATE (des48:Design {id: "DES048", name: "Interference Shield", description: "Shields interference", status: "Delayed", source: "Pront"})
CREATE (des49:Design {id: "DES049", name: "Flux Capacitor", description: "Stores quantum flux", status: "Delayed", source: "Pront"}) // Back to the Future nod
CREATE (des50:Design {id: "DES050", name: "Temporal Adjuster", description: "Adjusts time dilation", status: "In Progress", source: "Pront"})
CREATE (des51:Design {id: "DES051", name: "Gravity Compensator", description: "Compensates gravity", status: "Complete", source: "Pront"})
CREATE (des52:Design {id: "DES052", name: "Energy Converter", description: "Converts flux energy", status: "Complete", source: "Pront"})
CREATE (des53:Design {id: "DES053", name: "Signal Booster", description: "Boosts final signal", status: "Complete", source: "Pront"})
CREATE (des54:Design {id: "DES054", name: "Stability Monitor", description: "Monitors stability", status: "Complete", source: "Pront"})
CREATE (des55:Design {id: "DES055", name: "Quantum Terminator", description: "Terminates flux chain", status: "Complete", source: "Pront"}) // The twist!

// Relationships for the Chain
CREATE (cr1)-[:SATISFIES]->(req36)
CREATE (req36)-[:IMPLEMENTED_BY]->(des36)
CREATE (des36)-[:DEPENDS_ON]->(des37)
CREATE (des37)-[:DEPENDS_ON]->(des38)
CREATE (des38)-[:DEPENDS_ON]->(des39)
CREATE (des39)-[:DEPENDS_ON]->(des40)
CREATE (des40)-[:DEPENDS_ON]->(des41)
CREATE (des41)-[:DEPENDS_ON]->(des42)
CREATE (des42)-[:DEPENDS_ON]->(des43)
CREATE (des43)-[:DEPENDS_ON]->(des44)
CREATE (des44)-[:DEPENDS_ON]->(des45)
CREATE (des45)-[:DEPENDS_ON]->(des46)
CREATE (des46)-[:DEPENDS_ON]->(des47)
CREATE (des47)-[:DEPENDS_ON]->(des48)
CREATE (des48)-[:DEPENDS_ON]->(des49)
CREATE (des49)-[:DEPENDS_ON]->(des50)
CREATE (des50)-[:DEPENDS_ON]->(des51)
CREATE (des51)-[:DEPENDS_ON]->(des52)
CREATE (des52)-[:DEPENDS_ON]->(des53)
CREATE (des53)-[:DEPENDS_ON]->(des54)
CREATE (des54)-[:DEPENDS_ON]->(des55)
